<script lang="ts">
  export let classes = "";
</script>

<pre class={`text-center calendar -z-50 ${classes ?? ""}`}>
<div>                        *                        </div><div>                       &gt;o&lt;                       </div><div>                      &gt;*&lt;&lt;&lt;                      </div><div>                     &gt;o&gt;&gt;@&lt;&lt;                     </div><div>                    &gt;&gt;@&gt;&gt;&gt;o&lt;&lt;                    </div><div>                   &gt;&gt;O&gt;*&lt;&lt;&lt;*&lt;&lt;                   </div><div>                  &gt;o&gt;&gt;&gt;o&gt;&gt;&gt;o&lt;@&lt;                  </div><div>                 &gt;o&lt;&lt;*&gt;&gt;@&gt;&gt;&gt;O&lt;&lt;&lt;                 </div><div>                &gt;&gt;@&lt;&lt;@&lt;&lt;@&gt;o&lt;o&lt;O&lt;&lt;                </div><div>               &gt;&gt;o&gt;&gt;o&lt;&lt;&lt;o&lt;O&lt;O&lt;O&lt;&lt;&lt;               </div><div>              &gt;&gt;@&gt;&gt;o&lt;*&lt;&lt;@&gt;&gt;O&lt;O&lt;@&lt;&lt;&lt;              </div><div>             &gt;&gt;o&gt;&gt;@&gt;&gt;*&lt;&lt;*&lt;&lt;*&lt;O&gt;&gt;@&lt;&lt;&lt;             </div><div>            &gt;&gt;o&lt;&lt;&lt;*&lt;*&gt;&gt;*&gt;@&gt;&gt;&gt;@&gt;*&lt;O&gt;@&lt;            </div><div>           &gt;*&gt;&gt;o&lt;&lt;@&gt;&gt;&gt;*&gt;O&gt;&gt;O&gt;&gt;*&gt;&gt;&gt;*&lt;@&lt;           </div><div>          &gt;&gt;@&lt;&lt;o&gt;&gt;&gt;o&lt;&lt;&lt;O&lt;&lt;&lt;@&gt;*&gt;*&gt;&gt;@&lt;&lt;&lt;&lt;          </div><div>         &gt;&gt;O&gt;*&gt;O&gt;&gt;O&gt;o&lt;&lt;o&lt;o&lt;&lt;&lt;O&gt;O&lt;O&gt;&gt;&gt;o&lt;&lt;         </div><div>        &gt;&gt;O&lt;&lt;o&lt;O&gt;&gt;o&lt;&lt;&lt;@&gt;&gt;@&lt;&lt;O&lt;&lt;&lt;o&gt;O&gt;&gt;&gt;*&lt;&lt;        </div><div>       &gt;&gt;@&gt;&gt;@&lt;&lt;&lt;o&gt;*&gt;*&gt;O&gt;&gt;*&lt;&lt;@&lt;@&gt;*&lt;&lt;*&lt;&lt;*&lt;&lt;&lt;       </div><div>      &gt;*&gt;&gt;O&gt;&gt;@&gt;&gt;&gt;@&lt;&lt;&lt;o&gt;O&lt;o&lt;o&lt;&lt;&lt;@&lt;*&lt;&lt;o&gt;O&gt;o&lt;&lt;      </div><div>     &gt;&gt;@&gt;&gt;o&lt;&lt;O&gt;&gt;&gt;@&lt;&lt;*&gt;&gt;@&gt;&gt;o&lt;o&gt;*&lt;&lt;o&gt;&gt;O&lt;O&lt;&lt;&lt;o&lt;     </div><div>    &gt;&gt;*&lt;&lt;&lt;@&lt;&lt;&lt;*&gt;&gt;o&lt;&lt;&lt;o&gt;&gt;*&lt;&lt;O&lt;&lt;&lt;o&lt;*&lt;&lt;o&gt;o&lt;&lt;&lt;O&lt;&lt;    </div><div>   &gt;&gt;O&gt;&gt;&gt;O&lt;&lt;&lt;*&lt;*&lt;&lt;o&gt;&gt;@&gt;&gt;&gt;*&lt;&lt;&lt;*&lt;@&gt;@&lt;o&lt;&lt;*&gt;&gt;*&lt;o&lt;&lt;   </div><div>  &gt;O&gt;&gt;@&gt;O&gt;*&gt;&gt;&gt;*&gt;@&lt;&lt;O&lt;*&lt;@&gt;&gt;&gt;*&lt;&lt;&lt;*&gt;&gt;&gt;O&lt;&lt;o&gt;O&lt;O&lt;o&lt;&lt;  </div><div> &gt;*&lt;&lt;&lt;*&gt;&gt;*&gt;&gt;&gt;O&gt;&gt;o&lt;o&gt;&gt;o&lt;&lt;&lt;*&lt;&lt;&lt;o&gt;o&gt;&gt;&gt;*&lt;&lt;*&lt;@&lt;&lt;O&lt;&lt;&lt;&lt; </div><div>&gt;O&gt;&gt;&gt;@&lt;&lt;&lt;O&lt;&lt;@&gt;&gt;@&gt;*&gt;*&lt;*&lt;&lt;&lt;@&gt;&gt;&gt;O&gt;o&lt;&lt;&lt;O&lt;O&gt;*&gt;*&lt;O&gt;&gt;@&lt;&lt;</div><div>                      |   |                             <br
    />                      |   |                             <br
    />           _  _ __ ___|___|___ __ _  _      </div></pre>

<style>
  .calendar {
    user-select: none;
  }
</style>
